[project]
name = "conference-back"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "F4976259 Joao Dos Prazeres Farias", email = "joaodosprazeres@bb.com.br" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
conference-back = "conference_back:main"

[tool.uv.workspace]
members = ["services/*", "libs/*"]

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
